require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'
pod 'Stripe', '~> 19.4.0'
pod 'GoogleSignIn', '~> 6.0.2'

pod 'tipsi-stripe', :path => '../node_modules/tipsi-stripe'
target 'suidaga' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => false
  )

  pod 'RNGoogleSignin', :path => '../node_modules/@react-native-google-signin/google-signin'

  pod 'react-native-stripe-payments', :path => '../node_modules/react-native-stripe-payments'

  target 'suidagaTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!({ 'Flipper' => '0.108.0' })

   post_install do |installer|
     react_native_post_install(installer)
   end
end
